# Generated by Django 6.0.1 on 2026-01-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(default='RW', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
