# Generated by Django 6.0.1 on 2026-02-20 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sale_partial_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.CharField(max_length=50)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('payment_method', models.CharField(default='mtn_momo', max_length=50)),
                ('provider', models.CharField(choices=[('MTN_MOMO', 'MTN MoMo')], default='MTN_MOMO', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('provider_status', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='api.subscriptionevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payment_transactions', to='api.tenant')),
            ],
        ),
    ]
