# Generated by Django 6.0.1 on 2026-02-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subscriptionpaymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpaymenttransaction',
            name='provider',
            field=models.CharField(choices=[('MTN_MOMO', 'MTN MoMo'), ('LANARI_PAY', 'Lanari Pay')], default='MTN_MOMO', max_length=30),
        ),
    ]
