# Generated by Django 6.0.1 on 2026-02-27 08:34

from django.db import migrations, models


def populate_sale_currency(apps, schema_editor):
    Sale = apps.get_model("api", "Sale")
    Tenant = apps.get_model("api", "Tenant")
    tenant_currency = dict(Tenant.objects.values_list("id", "currency"))

    for sale in Sale.objects.all().only("id", "tenant_id", "currency"):
        currency = (tenant_currency.get(sale.tenant_id) or sale.currency or "USD")
        currency = str(currency).strip().upper() or "USD"
        if sale.currency != currency:
            Sale.objects.filter(id=sale.id).update(currency=currency)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_subscriptionpaymenttransaction_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.RunPython(populate_sale_currency, noop_reverse),
    ]
