# Generated by Django 6.0.1 on 2026-03-17 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sale_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('WHOLESALE', 'WHOLESALE')], default='WHOLESALE', max_length=20),
        ),
        migrations.CreateModel(
            name='RetailWholesaleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_wholesale_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_wholesale_requests_created', to=settings.AUTH_USER_MODEL)),
                ('retail_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_outgoing_requests', to='api.tenant')),
                ('wholesale_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_incoming_requests', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RetailWholesaleRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.retailwholesalerequest')),
            ],
        ),
    ]
