# Generated by Django 6.0.1 on 2026-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_department_retailwholesalerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailwholesalerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OWNER_APPROVED', 'Owner Approved'), ('STOCK_CONFIRMED', 'Stock Confirmed'), ('PHARMACIST_APPROVED', 'Pharmacist Approved'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID_PENDING_CONFIRMATION', 'Paid Pending Confirmation'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('READY_FOR_DELIVERY', 'Ready For Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32),
        ),
    ]
