# Generated by Django 6.0.1 on 2026-03-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_retailwholesalerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_created_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_created_stock_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
