# Generated by Django 6.0.1 on 2026-03-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_medicine_created_by_stockbatch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='source_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_stock_batches', to='api.retailwholesalerequest'),
        ),
    ]
