# Generated by Django 6.0.1 on 2026-10-05 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_user_firebase_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('pricing_method', models.CharField(choices=[('file', 'Selling price from file'), ('markup', 'Cost price plus markup'), ('manual', 'Entered manually')], default='file', max_length=10)),
                ('markup_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('missing_batch_strategy', models.CharField(choices=[('manual', 'Fix missing batch numbers manually'), ('generate', 'Generate internal batch numbers')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_imports', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('removed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.medicineimportsession')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIVE', 'Stock received'), ('IMPORT', 'Imported from file'), ('ADJUSTMENT', 'Manual adjustment'), ('TRANSFER_OUT', 'Transferred out')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.stockbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='api.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
