# Generated by Django 6.0.1 on 2026-10-05 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_stock_movements_and_medicine_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_key', models.CharField(max_length=255)),
                ('target_field', models.CharField(max_length=30)),
                ('times_used', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_column_mappings', to='api.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'header_key'), name='unique_import_mapping_per_tenant_header')],
            },
        ),
    ]
