# Generated by Django 6.0.1 on 2026-10-05 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_import_column_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='permission_overrides',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('base_role', models.CharField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('CASHIER', 'CASHIER'), ('STORE_KEEPER', 'STORE_KEEPER'), ('ACCOUNTANT', 'ACCOUNTANT'), ('PHARMACIST', 'PHARMACIST')], max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='usertenant',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='api.tenantrole'),
        ),
        migrations.AddConstraint(
            model_name='tenantrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name_per_tenant'),
        ),
    ]
