from datetime import datetime


PAGE_WIDTH = 595
PAGE_HEIGHT = 842
MARGIN = 42
GREEN = (0.05, 0.53, 0.22)
LIGHT_GREEN = (0.92, 0.97, 0.93)
TEXT = (0.12, 0.16, 0.14)
MUTED = (0.32, 0.39, 0.35)
LINE = (0.66, 0.82, 0.70)


def _escape(value):
    value = "" if value is None else str(value)
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _rgb(color):
    return f"{color[0]:.3f} {color[1]:.3f} {color[2]:.3f}"


class _PdfCanvas:
    def __init__(self):
        self.pages = []
        self.current = []
        self.page_number = 0
        self.new_page()

    def new_page(self):
        if self.current:
            self._footer()
        self.page_number += 1
        self.current = []
        self.pages.append(self.current)

    def _footer(self):
        self.set_stroke(GREEN)
        self.line(MARGIN, 54, PAGE_WIDTH - MARGIN, 54)
        self.text(MARGIN, 35, "Generated by Pharmalinkr", 7, MUTED)
        self.text(PAGE_WIDTH / 2 - 20, 35, f"Page {self.page_number}", 7, MUTED)

    def finish(self):
        self._footer()
        return self.pages

    def add(self, command):
        self.current.append(command)

    def set_fill(self, color):
        self.add(f"{_rgb(color)} rg")

    def set_stroke(self, color):
        self.add(f"{_rgb(color)} RG")

    def text(self, x, y, value, size=9, color=TEXT, bold=False):
        font = "F2" if bold else "F1"
        self.set_fill(color)
        self.add(f"BT /{font} {size} Tf {x:.2f} {y:.2f} Td ({_escape(value)}) Tj ET")

    def rect(self, x, y, width, height, fill=None, stroke=None):
        if fill:
            self.set_fill(fill)
        if stroke:
            self.set_stroke(stroke)
        op = "B" if fill and stroke else "f" if fill else "S"
        self.add(f"{x:.2f} {y:.2f} {width:.2f} {height:.2f} re {op}")

    def line(self, x1, y1, x2, y2):
        self.add(f"{x1:.2f} {y1:.2f} m {x2:.2f} {y2:.2f} l S")


def _wrap(value, max_chars):
    value = "" if value is None else str(value)
    if len(value) <= max_chars:
        return [value]
    words = value.split()
    lines = []
    line = ""
    for word in words:
        candidate = f"{line} {word}".strip()
        if len(candidate) <= max_chars:
            line = candidate
        else:
            if line:
                lines.append(line)
            line = word[:max_chars]
    if line:
        lines.append(line)
    return lines or [value[:max_chars]]


def _draw_header(canvas, report):
    branding = report.get("branding", {})
    canvas.rect(0, PAGE_HEIGHT - 18, PAGE_WIDTH, 18, fill=GREEN)
    canvas.rect(MARGIN, PAGE_HEIGHT - 105, 8, 72, fill=GREEN)
    canvas.text(MARGIN + 28, PAGE_HEIGHT - 52, branding.get("name", "Pharmalinkr Pharmacy").upper(), 14, GREEN, True)
    canvas.text(MARGIN + 28, PAGE_HEIGHT - 68, branding.get("address", ""), 8, TEXT)
    canvas.text(MARGIN + 28, PAGE_HEIGHT - 81, branding.get("phone", ""), 8, TEXT)
    canvas.text(MARGIN + 28, PAGE_HEIGHT - 94, branding.get("email", ""), 8, TEXT)
    canvas.text(PAGE_WIDTH - 250, PAGE_HEIGHT - 68, report.get("title", "Financial Performance Report"), 14, GREEN, True)
    canvas.text(PAGE_WIDTH - 250, PAGE_HEIGHT - 85, report.get("period", ""), 8, TEXT)
    canvas.line(MARGIN, PAGE_HEIGHT - 118, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 118)


def _ensure_space(canvas, y, needed, report):
    if y - needed >= 75:
        return y
    canvas.new_page()
    _draw_header(canvas, report)
    return PAGE_HEIGHT - 150


def _draw_summary(canvas, y, report):
    summary = report.get("summary", {})
    fields = [
        ("Total Revenue", summary.get("totalRevenue")),
        ("Total Expenses", summary.get("totalExpenses")),
        ("Gross Profit", summary.get("grossProfit")),
        ("Net Profit", summary.get("netProfit")),
        ("Profit Margin", f"{summary.get('profitMargin', 0)}%"),
        ("Transactions", summary.get("transactions")),
        ("Inventory Value", summary.get("inventoryValue")),
        ("Expired Stock Loss", summary.get("expiredStockLoss")),
    ]
    canvas.text(MARGIN, y, "Report Summary", 10, GREEN, True)
    y -= 18
    col_width = (PAGE_WIDTH - (MARGIN * 2)) / 2
    for index, (label, value) in enumerate(fields):
        x = MARGIN if index % 2 == 0 else MARGIN + col_width + 20
        row_y = y - (index // 2) * 18
        canvas.text(x, row_y, f"{label}:", 8, TEXT, True)
        canvas.text(x + 112, row_y, value, 8, TEXT)
    y -= 88
    canvas.line(MARGIN, y + 12, PAGE_WIDTH - MARGIN, y + 12)
    return y


def _row_values(row):
    if "category" in row:
        return [row.get("category"), row.get("revenue"), row.get("percentage")]
    if "type" in row:
        return [row.get("type"), row.get("amount"), row.get("percentage")]
    if "description" in row:
        return [row.get("description"), row.get("amount")]
    if "medicine" in row:
        return [row.get("medicine"), row.get("qtySold"), row.get("revenue")]
    if "reason" in row:
        return [row.get("reason"), row.get("value"), row.get("count")]
    return list(row.values())


def _draw_table(canvas, y, section, report):
    y = _ensure_space(canvas, y, 52, report)
    canvas.text(MARGIN, y, section.get("title", ""), 10, GREEN, True)
    y -= 18

    columns = section.get("columns", [])
    rows = section.get("rows", [])
    table_width = PAGE_WIDTH - (MARGIN * 2)
    first_col = table_width * 0.50
    other_width = (table_width - first_col) / max(len(columns) - 1, 1)
    widths = [first_col] + [other_width] * (len(columns) - 1)

    canvas.rect(MARGIN, y - 14, table_width, 18, fill=LIGHT_GREEN, stroke=LINE)
    x = MARGIN + 5
    for index, column in enumerate(columns):
        canvas.text(x, y - 8, column, 7, GREEN, True)
        x += widths[index]
    y -= 18

    for row in rows:
        values = _row_values(row)
        y = _ensure_space(canvas, y, 20, report)
        row_height = 18
        canvas.rect(MARGIN, y - 14, table_width, row_height, stroke=LINE)
        x = MARGIN + 5
        for index, value in enumerate(values[: len(columns)]):
            text = value
            if columns[index].startswith("%") and isinstance(value, (int, float)):
                text = f"{value}%"
            max_chars = 40 if index == 0 else 18
            canvas.text(x, y - 8, _wrap(text, max_chars)[0], 7, TEXT, index == 0 and str(text).lower().startswith("total"))
            x += widths[index]
        y -= row_height
    return y - 12


def _build_pdf(pages):
    objects = []

    def add_object(content):
        objects.append(content)
        return len(objects)

    page_refs = []
    content_refs = []
    font_regular_ref = None
    font_bold_ref = None

    catalog_ref = add_object("<< /Type /Catalog /Pages 2 0 R >>")
    pages_ref = add_object("")
    font_regular_ref = add_object("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    font_bold_ref = add_object("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")

    for page in pages:
        stream = "\n".join(page).encode("utf-8")
        content_ref = add_object(f"<< /Length {len(stream)} >>\nstream\n{stream.decode('utf-8')}\nendstream")
        content_refs.append(content_ref)
        page_ref = add_object(
            f"<< /Type /Page /Parent {pages_ref} 0 R /MediaBox [0 0 {PAGE_WIDTH} {PAGE_HEIGHT}] "
            f"/Resources << /Font << /F1 {font_regular_ref} 0 R /F2 {font_bold_ref} 0 R >> >> "
            f"/Contents {content_ref} 0 R >>"
        )
        page_refs.append(page_ref)

    objects[pages_ref - 1] = f"<< /Type /Pages /Kids [{' '.join(f'{ref} 0 R' for ref in page_refs)}] /Count {len(page_refs)} >>"

    output = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{index} 0 obj\n{obj}\nendobj\n".encode("utf-8"))
    xref = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n".encode("utf-8"))
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode("utf-8"))
    output.extend(f"trailer\n<< /Size {len(objects) + 1} /Root {catalog_ref} 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode("utf-8"))
    return bytes(output)


def render_report_pdf(report):
    canvas = _PdfCanvas()
    _draw_header(canvas, report)
    y = PAGE_HEIGHT - 145
    y = _draw_summary(canvas, y, report)
    for section in report.get("sections", []):
        y = _draw_table(canvas, y, section, report)

    canvas.text(MARGIN, 22, f"Generated on: {datetime.now().strftime('%b %d, %Y %I:%M %p')}", 7, MUTED)
    pages = canvas.finish()
    return _build_pdf(pages)
