from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView
from .views import RegisterTenantView,RegisterOwnerView, LoginView, LogoutView,SelectTenantView,CreateUserView, OwnerUserListView,OwnerUpdateUserView,OwnerUserStatusView,OwnerResetUserPasswordView,UsersSummaryView,SearchUsersView,RolesListView,ChangePasswordView, OwnerUsersDashboardView, OwnerNotificationsView, OwnerNotificationDetailView, OwnerNotificationsDashboardView, OwnerDashboardView, OwnerDashboardSummaryView, OwnerDashboardSalesTrendView, OwnerDashboardPartialInvoicesView, OwnerTenantsListView, OwnerSwitchTenantView, PharmacySettingsView, OwnerPharmaciesView, OwnerSettingsOverviewView, OwnerSettingsConsolidatedView, OwnerInvoicesListView, OwnerInvoiceDetailView, OwnerInvoicesSummaryView, OwnerInvoicesDashboardView, OwnerApprovePartialInvoiceView, OwnerRejectPartialInvoiceView, OwnerInventoryView, OwnerInventorySummaryView, OwnerInventoryMedicineDetailView, OwnerSalesDashboardView, OwnerSalesSummaryView, OwnerDailySalesTrendView, OwnerPaymentMethodsDistributionView, OwnerExportSalesView, OwnerSalesReportsDashboardView, OwnerUserManagementReportView, OwnerUsersSummaryCardsView, SupportTicketViewSet
from .views.storekeeper.inventory import InventoryListCreateView
from .views.storekeeper.expiry_alerts import ExpiryAlertsView, ExpiryAlertsSummaryView, ExpiryAlertsCriticalView, ExpiredBatchesView
from .views.cashier.dashboard import CashierDashboardSummaryView, CashierStockAlertsView, CashierAvailableMedicinesView, CashierPendingRequestsView, CashierExpiryAlertsView
from .views.cashier.inventory import CashierInventoryListView
from .views.cashier.sales import CashierCreateSaleView, CashierSalesListView, CashierSalesDetailView, StorekeeperApproveSaleView, StorekeeperRejectSaleView, StorekeeperPendingSalesView
from .views.cashier.history import CashierHistorySummaryView, CashierSalesHistoryView, CashierSalesChartDataView, CashierCompletedSalesView, CashierPartialPaymentSalesView, CashierStockRequestsView
from .views.accountant.invoices import AccountantInvoicesListView, AccountantInvoiceDetailView, AccountantApproveInvoiceView, AccountantRecordPartialPaymentView, AccountantMarkFullyPaidView, AccountantInvoicesSummaryView, AccountantInvoicesReportView
from .views.accountant.sales import AccountantSalesSummaryView, AccountantDailySalesTrendView, AccountantPaymentMethodsDistributionView, AccountantExportSalesView
from .views.accountant.expenses import AccountantExpensesListCreateView, AccountantExpenseDetailView, AccountantExpensesSummaryView
from .views.accountant.reports import AccountantFinancialReportView, AccountantInventoryReportView, AccountantSalesReportView, AccountantExportReportView
from .views.accountant.history import AccountantDashboardSummaryView, AccountantRecentNotificationsView, AccountantApprovedSalesListView, AccountantMarkNotificationAsReadView, AccountantMarkAllNotificationsAsReadView
from .views.accountant.analytics import AccountantAnalyticsDashboardView, AccountantAnalyticsKPIView, AccountantAnalyticsTrendsView, AccountantAnalyticsForecastsView, AccountantAnalyticsInsightsView
from .views.accountant.dashboard import AccountantDashboardPaymentsView, AccountantPendingPartialPaymentsView, AccountantOverduePaymentsView, AccountantTotalPaidAmountView, AccountantSelectedForInvoiceView, AccountantPartialPaymentRequestsView, AccountantQuickStatsView, PartialInvoiceReminderConfigView, PartialInvoiceReminderSendView, PartialInvoiceReminderHistoryView
from .views.pharmacist.invoices import PharmacistInvoicesListView, PharmacistInvoiceDetailView, PharmacistInvoicesSummaryView, PharmacistApproveInvoiceView, PharmacistPaymentApprovalsListView, PharmacistApprovePaymentView, PharmacistInvoiceQuickStatsView
from .views.pharmacist.partial_payments import PharmacistPartialPaymentsListView, PharmacistPartialPaymentSummaryView, PharmacistApprovePartialPaymentView, PharmacistRejectPartialPaymentView
from .views.pharmacist.history import PharmacistApprovalHistoryListView, PharmacistHistorySummaryView, PharmacistHistoryExportView, PharmacistHistorySearchView
from .views.pharmacist.dashboard import PharmacistDashboardSummaryView, PharmacistPendingInvoicesView, PharmacistRecentApprovalsView
from .views.role_notifications import (
    StorekeeperRecentNotificationsView,
    StorekeeperMarkNotificationAsReadView,
    StorekeeperMarkAllNotificationsAsReadView,
    CashierRecentNotificationsView,
    CashierMarkNotificationAsReadView,
    CashierMarkAllNotificationsAsReadView,
    PharmacistRecentNotificationsView,
    PharmacistMarkNotificationAsReadView,
    PharmacistMarkAllNotificationsAsReadView,
)
from .views.owner.partial_payments import OwnerPartialPaymentsListView, OwnerPartialPaymentSummaryView, OwnerApprovePartialPaymentView, OwnerRejectPartialPaymentView
from .views.pricing import PricingPlansView, PricingCompareView, PricingFAQView, PricingCalculateUpgradeView, PricingRecommendationView, SubscriptionPlansView, SubscriptionPlanDetailView, SubscriptionHistoryView, SubscriptionUpgradeView, SubscriptionDowngradeView, SubscriptionCancelView, SubscriptionTrialRenewView, SubscriptionTrialStatusView, SubscriptionLimitsView, SubscriptionFeatureView, SubscriptionUsageView, SubscriptionPaymentView, SubscriptionPaymentStatusView, SubscriptionMtnWebhookView, SubscriptionInvoicesView, SubscriptionInvoiceDownloadView
from .views.retail import RetailMedicinesView, RetailSalesView, RetailInsuranceSalesView, RetailExpensesView, RetailStockView, RetailExpiringMedicinesView, RetailLowStockView, RetailDashboardView, RetailReportsView, RetailExpenseDeleteView, CollaborativeRetailWholesaleCatalogView
from .views.retail_wholesale import RetailWholesaleRequestListCreateView, RetailWholesaleRequestDecisionView
from .views.super_admin import SuperAdminMetricsView, SuperAdminTenantsView, SuperAdminTenantDetailView, SuperAdminTenantStatusView, SuperAdminSubscriptionsView, SuperAdminSubscriptionDetailView, SuperAdminSubscriptionPlanView, SuperAdminExtendTrialView, SuperAdminExpireSubscriptionView, SuperAdminCancelSubscriptionView, SuperAdminUsersView, SuperAdminPlansView, SuperAdminPlanDetailView, SuperAdminAuditLogsView, SuperAdminSettingsView

router = DefaultRouter()
router.register(r"support-tickets", SupportTicketViewSet, basename="support-ticket")

urlpatterns = [
    path("register-tenant/", RegisterTenantView.as_view()),
    path("login/", LoginView.as_view(),name="login"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
    path("pricing/plans/", PricingPlansView.as_view(), name="pricing-plans"),
    path("pricing/compare/", PricingCompareView.as_view(), name="pricing-compare"),
    path("pricing/calculate-upgrade/", PricingCalculateUpgradeView.as_view(), name="pricing-calculate-upgrade"),
    path("pricing/recommend/", PricingRecommendationView.as_view(), name="pricing-recommend"),
    path("pricing/faq/", PricingFAQView.as_view(), name="pricing-faq"),
    path("subscriptions/plans/", SubscriptionPlansView.as_view(), name="subscriptions-plans"),
    path("subscriptions/plans/<str:plan_id>/", SubscriptionPlanDetailView.as_view(), name="subscriptions-plan-detail"),
    path("subscriptions/history/", SubscriptionHistoryView.as_view(), name="subscriptions-history"),
    path("subscriptions/upgrade/", SubscriptionUpgradeView.as_view(), name="subscriptions-upgrade"),
    path("subscriptions/downgrade/", SubscriptionDowngradeView.as_view(), name="subscriptions-downgrade"),
    path("subscriptions/cancel/", SubscriptionCancelView.as_view(), name="subscriptions-cancel"),
    path("subscriptions/trial/renew/", SubscriptionTrialRenewView.as_view(), name="subscriptions-trial-renew"),
    path("subscriptions/trial/status/", SubscriptionTrialStatusView.as_view(), name="subscriptions-trial-status"),
    path("subscriptions/limits/", SubscriptionLimitsView.as_view(), name="subscriptions-limits"),
    path("subscriptions/features/<str:feature_name>/", SubscriptionFeatureView.as_view(), name="subscriptions-feature"),
    path("subscriptions/usage/", SubscriptionUsageView.as_view(), name="subscriptions-usage"),
    path("subscriptions/payment/", SubscriptionPaymentView.as_view(), name="subscriptions-payment"),
    path("subscriptions/payment-status/<uuid:transaction_id>/", SubscriptionPaymentStatusView.as_view(), name="subscriptions-payment-status"),
    path("subscriptions/payment/mtn/webhook/", SubscriptionMtnWebhookView.as_view(), name="subscriptions-payment-mtn-webhook"),
    path("subscriptions/invoices/", SubscriptionInvoicesView.as_view(), name="subscriptions-invoices"),
    path("subscriptions/invoices/<uuid:invoice_id>/download/", SubscriptionInvoiceDownloadView.as_view(), name="subscriptions-invoice-download"),
    path("retails/medicines", RetailMedicinesView.as_view(), name="retails-medicines-no-slash"),
    path("retails/medicines/", RetailMedicinesView.as_view(), name="retails-medicines"),
    path("retails/wholesale-catalog", CollaborativeRetailWholesaleCatalogView.as_view(), name="retails-wholesale-catalog-no-slash"),
    path("retails/wholesale-catalog/", CollaborativeRetailWholesaleCatalogView.as_view(), name="retails-wholesale-catalog"),
    path("retails/sales", RetailSalesView.as_view(), name="retails-sales-no-slash"),
    path("retails/sales/", RetailSalesView.as_view(), name="retails-sales"),
    path("retails/insurance-sales", RetailInsuranceSalesView.as_view(), name="retails-insurance-sales-no-slash"),
    path("retails/insurance-sales/", RetailInsuranceSalesView.as_view(), name="retails-insurance-sales"),
    path("retails/expenses", RetailExpensesView.as_view(), name="retails-expenses-no-slash"),
    path("retails/expenses/", RetailExpensesView.as_view(), name="retails-expenses"),
    path("retails/expenses/<uuid:expense_id>", RetailExpenseDeleteView.as_view(), name="retails-expense-delete-no-slash"),
    path("retails/expenses/<uuid:expense_id>/", RetailExpenseDeleteView.as_view(), name="retails-expense-delete"),
    path("retails/stock", RetailStockView.as_view(), name="retails-stock-no-slash"),
    path("retails/stock/", RetailStockView.as_view(), name="retails-stock"),
    path("retails/expiring-medicines", RetailExpiringMedicinesView.as_view(), name="retails-expiring-medicines-no-slash"),
    path("retails/expiring-medicines/", RetailExpiringMedicinesView.as_view(), name="retails-expiring-medicines"),
    path("retails/low-stock", RetailLowStockView.as_view(), name="retails-low-stock-no-slash"),
    path("retails/low-stock/", RetailLowStockView.as_view(), name="retails-low-stock"),
    path("retails/dashboard", RetailDashboardView.as_view(), name="retails-dashboard-no-slash"),
    path("retails/dashboard/", RetailDashboardView.as_view(), name="retails-dashboard"),
    path("retails/reports", RetailReportsView.as_view(), name="retails-reports-no-slash"),
    path("retails/reports/", RetailReportsView.as_view(), name="retails-reports"),
    path("retail-wholesale/requests/", RetailWholesaleRequestListCreateView.as_view(), name="retail-wholesale-requests"),
    path("retail-wholesale/requests/<uuid:request_id>/decision/", RetailWholesaleRequestDecisionView.as_view(), name="retail-wholesale-request-decision"),
    path("super-admin/metrics/", SuperAdminMetricsView.as_view(), name="super-admin-metrics"),
    path("super-admin/tenants/", SuperAdminTenantsView.as_view(), name="super-admin-tenants"),
    path("super-admin/tenants/<uuid:tenant_id>/", SuperAdminTenantDetailView.as_view(), name="super-admin-tenant-detail"),
    path("super-admin/tenants/<uuid:tenant_id>/status/", SuperAdminTenantStatusView.as_view(), name="super-admin-tenant-status"),
    path("super-admin/subscriptions/", SuperAdminSubscriptionsView.as_view(), name="super-admin-subscriptions"),
    path("super-admin/subscriptions/<int:subscription_id>/", SuperAdminSubscriptionDetailView.as_view(), name="super-admin-subscription-detail"),
    path("super-admin/subscriptions/<int:subscription_id>/plan/", SuperAdminSubscriptionPlanView.as_view(), name="super-admin-subscription-plan"),
    path("subscriptions/<int:subscription_id>/extend-trial/", SuperAdminExtendTrialView.as_view(), name="subscription-extend-trial"),
    path("super-admin/subscriptions/<int:subscription_id>/expire/", SuperAdminExpireSubscriptionView.as_view(), name="super-admin-subscription-expire"),
    path("super-admin/subscriptions/<int:subscription_id>/cancel/", SuperAdminCancelSubscriptionView.as_view(), name="super-admin-subscription-cancel"),
    path("super-admin/users/", SuperAdminUsersView.as_view(), name="super-admin-users"),
    path("super-admin/plans/", SuperAdminPlansView.as_view(), name="super-admin-plans"),
    path("super-admin/plans/<uuid:plan_id>/", SuperAdminPlanDetailView.as_view(), name="super-admin-plan-detail"),
    path("super-admin/audit-logs/", SuperAdminAuditLogsView.as_view(), name="super-admin-audit-logs"),
    path("super-admin/settings/", SuperAdminSettingsView.as_view(), name="super-admin-settings"),
    path("change-password/", ChangePasswordView.as_view(),name="change-password"),
    path("logout/", LogoutView.as_view()),
    path("select-tenant/", SelectTenantView.as_view(),name="select-tenant"),
    path("owner/create-user/", CreateUserView.as_view(),name="create-user"),
    path("owner/users/dashboard/", OwnerUsersDashboardView.as_view(), name="owner-users-dashboard"),
    path("owner/users/", OwnerUserListView.as_view(), name="users"),
    path("owner/users/<uuid:user_id>/", OwnerUpdateUserView.as_view(), name="update-user"),
    path("owner/users/<uuid:user_id>/status/", OwnerUserStatusView.as_view(), name="user-status"),
    path("owner/users/<uuid:user_id>/reset-password/", OwnerResetUserPasswordView.as_view(), name="reset-password"),
    path("users/summary/", UsersSummaryView.as_view(), name="users-summary"),
    path("owner/notifications/", OwnerNotificationsView.as_view(), name="owner-notifications"),
    path("owner/notifications/dashboard/", OwnerNotificationsDashboardView.as_view(), name="owner-notifications-dashboard"),
    path("owner/notifications/<uuid:notification_id>/", OwnerNotificationDetailView.as_view(), name="owner-notification-detail"),
    path("owner/dashboard/", OwnerDashboardView.as_view(), name="owner-dashboard"),
    path("owner/dashboard/summary/", OwnerDashboardSummaryView.as_view(), name="owner-dashboard-summary"),
    path("owner/dashboard/sales-trend/", OwnerDashboardSalesTrendView.as_view(), name="owner-dashboard-sales-trend"),
    path("owner/dashboard/partial-invoices/", OwnerDashboardPartialInvoicesView.as_view(), name="owner-dashboard-partial-invoices"),
    path("owner/invoices/", OwnerInvoicesListView.as_view(), name="owner-invoices"),
    path("owner/invoices/dashboard/", OwnerInvoicesDashboardView.as_view(), name="owner-invoices-dashboard"),
    path("owner/invoices/summary/", OwnerInvoicesSummaryView.as_view(), name="owner-invoices-summary"),
    path("owner/invoices/<uuid:invoice_id>/", OwnerInvoiceDetailView.as_view(), name="owner-invoice-detail"),
    path("owner/invoices/<uuid:invoice_id>/approve/", OwnerApprovePartialInvoiceView.as_view(), name="owner-invoice-approve"),
    path("owner/invoices/<uuid:invoice_id>/reject/", OwnerRejectPartialInvoiceView.as_view(), name="owner-invoice-reject"),
    path("owner/inventory/", OwnerInventoryView.as_view(), name="owner-inventory"),
    path("owner/inventory/summary/", OwnerInventorySummaryView.as_view(), name="owner-inventory-summary"),
    path("owner/inventory/<uuid:medicine_id>/", OwnerInventoryMedicineDetailView.as_view(), name="owner-inventory-medicine-detail"),
    path("owner/sales/", OwnerSalesDashboardView.as_view(), name="owner-sales-dashboard"),
    path("owner/sales/summary/", OwnerSalesSummaryView.as_view(), name="owner-sales-summary"),
    path("owner/sales/daily-trend/", OwnerDailySalesTrendView.as_view(), name="owner-sales-daily-trend"),
    path("owner/sales/payment-distribution/", OwnerPaymentMethodsDistributionView.as_view(), name="owner-sales-payment-distribution"),
    path("owner/sales/export/", OwnerExportSalesView.as_view(), name="owner-sales-export"),
    path("owner/tenants/", OwnerTenantsListView.as_view(), name="owner-tenants"),
    path("owner/tenants/switch/", OwnerSwitchTenantView.as_view(), name="owner-tenants-switch"),
    path("owner/settings/", OwnerSettingsOverviewView.as_view(), name="owner-settings-overview"),
    path("owner/settings/consolidated/", OwnerSettingsConsolidatedView.as_view(), name="owner-settings-consolidated"),
    path("owner/settings/pharmacy/", PharmacySettingsView.as_view(), name="owner-settings-pharmacy"),
    path("owner/settings/pharmacies/", OwnerPharmaciesView.as_view(), name="owner-settings-pharmacies"),
    path("owner/reports/", OwnerSalesReportsDashboardView.as_view(), name="owner-reports-dashboard"),
    path("owner/reports/user-management/", OwnerUserManagementReportView.as_view(), name="owner-reports-user-management"),
    path("owner/reports/user-management/summary/", OwnerUsersSummaryCardsView.as_view(), name="owner-reports-user-management-summary"),
    path("storekeeper/inventory/", InventoryListCreateView.as_view(), name="storekeeper-inventory"),
    path("storekeeper/expiry-alerts/", ExpiryAlertsView.as_view(), name="storekeeper-expiry-alerts"),
    path("storekeeper/expiry-alerts/summary/", ExpiryAlertsSummaryView.as_view(), name="storekeeper-expiry-alerts-summary"),
    path("storekeeper/expiry-alerts/critical/", ExpiryAlertsCriticalView.as_view(), name="storekeeper-expiry-alerts-critical"),
    path("storekeeper/expiry-alerts/expired/", ExpiredBatchesView.as_view(), name="storekeeper-expired-batches"),
    path("storekeeper/notifications/", StorekeeperRecentNotificationsView.as_view(), name="storekeeper-notifications"),
    path("storekeeper/notifications/<uuid:notification_id>/read/", StorekeeperMarkNotificationAsReadView.as_view(), name="storekeeper-mark-notification-read"),
    path("storekeeper/notifications/read-all/", StorekeeperMarkAllNotificationsAsReadView.as_view(), name="storekeeper-mark-all-notifications-read"),
    path("cashier/dashboard/", CashierDashboardSummaryView.as_view(), name="cashier-dashboard"),
    path("cashier/stock-alerts/", CashierStockAlertsView.as_view(), name="cashier-stock-alerts"),
    path("cashier/medicines/", CashierAvailableMedicinesView.as_view(), name="cashier-medicines"),
    path("cashier/inventory/", CashierInventoryListView.as_view(), name="cashier-inventory"),
    path("cashier/pending-requests/", CashierPendingRequestsView.as_view(), name="cashier-pending-requests"),
    path("cashier/expiry-alerts/", CashierExpiryAlertsView.as_view(), name="cashier-expiry-alerts"),
    path("cashier/sales/", CashierCreateSaleView.as_view(), name="cashier-create-sale"),
    path("cashier/sales/list/", CashierSalesListView.as_view(), name="cashier-sales-list"),
    path("cashier/sales/<uuid:sale_id>/", CashierSalesDetailView.as_view(), name="cashier-sales-detail"),
    path("storekeeper/sales/pending/", StorekeeperPendingSalesView.as_view(), name="storekeeper-pending-sales"),
    path("storekeeper/sales/<uuid:sale_id>/approve/", StorekeeperApproveSaleView.as_view(), name="storekeeper-approve-sale"),
    path("storekeeper/sales/<uuid:sale_id>/reject/", StorekeeperRejectSaleView.as_view(), name="storekeeper-reject-sale"),
    path("cashier/history/summary/", CashierHistorySummaryView.as_view(), name="cashier-history-summary"),
    path("cashier/history/sales/", CashierSalesHistoryView.as_view(), name="cashier-history-sales"),
    path("cashier/history/chart-data/", CashierSalesChartDataView.as_view(), name="cashier-history-chart-data"),
    path("cashier/history/completed/", CashierCompletedSalesView.as_view(), name="cashier-history-completed"),
    path("cashier/history/partial-payments/", CashierPartialPaymentSalesView.as_view(), name="cashier-history-partial-payments"),
    path("cashier/history/stock-requests/", CashierStockRequestsView.as_view(), name="cashier-history-stock-requests"),
    path("cashier/notifications/", CashierRecentNotificationsView.as_view(), name="cashier-notifications"),
    path("cashier/notifications/<uuid:notification_id>/read/", CashierMarkNotificationAsReadView.as_view(), name="cashier-mark-notification-read"),
    path("cashier/notifications/read-all/", CashierMarkAllNotificationsAsReadView.as_view(), name="cashier-mark-all-notifications-read"),
    path("accountant/invoices/", AccountantInvoicesListView.as_view(), name="accountant-invoices"),
    path("accountant/invoices/<uuid:sale_id>/", AccountantInvoiceDetailView.as_view(), name="accountant-invoice-detail"),
    path("accountant/invoices/<uuid:sale_id>/approve/", AccountantApproveInvoiceView.as_view(), name="accountant-approve-invoice"),
    path("accountant/invoices/<uuid:sale_id>/partial-payment/", AccountantRecordPartialPaymentView.as_view(), name="accountant-partial-payment"),
    path("accountant/invoices/<uuid:sale_id>/mark-paid/", AccountantMarkFullyPaidView.as_view(), name="accountant-mark-paid"),
    path("accountant/invoices/summary/", AccountantInvoicesSummaryView.as_view(), name="accountant-invoices-summary"),
    path("accountant/invoices/report/", AccountantInvoicesReportView.as_view(), name="accountant-invoices-report"),
    path("accountant/sales/summary/", AccountantSalesSummaryView.as_view(), name="accountant-sales-summary"),
    path("accountant/sales/daily-trend/", AccountantDailySalesTrendView.as_view(), name="accountant-sales-daily-trend"),
    path("accountant/sales/payment-distribution/", AccountantPaymentMethodsDistributionView.as_view(), name="accountant-sales-payment-distribution"),
    path("accountant/sales/export/", AccountantExportSalesView.as_view(), name="accountant-sales-export"),
    path("accountant/expenses/", AccountantExpensesListCreateView.as_view(), name="accountant-expenses-list-create"),
    path("accountant/expenses/<uuid:expense_id>/", AccountantExpenseDetailView.as_view(), name="accountant-expense-detail"),
    path("accountant/expenses/summary/", AccountantExpensesSummaryView.as_view(), name="accountant-expenses-summary"),
    path("accountant/reports/financial/", AccountantFinancialReportView.as_view(), name="accountant-reports-financial"),
    path("accountant/reports/inventory/", AccountantInventoryReportView.as_view(), name="accountant-reports-inventory"),
    path("accountant/reports/sales/", AccountantSalesReportView.as_view(), name="accountant-reports-sales"),
    path("accountant/reports/export/", AccountantExportReportView.as_view(), name="accountant-reports-export"),
    path("accountant/dashboard/", AccountantDashboardSummaryView.as_view(), name="accountant-dashboard"),
    path("accountant/notifications/", AccountantRecentNotificationsView.as_view(), name="accountant-notifications"),
    path("accountant/approved-sales/", AccountantApprovedSalesListView.as_view(), name="accountant-approved-sales"),
    path("accountant/notifications/<uuid:notification_id>/read/", AccountantMarkNotificationAsReadView.as_view(), name="accountant-mark-notification-read"),
    path("accountant/notifications/read-all/", AccountantMarkAllNotificationsAsReadView.as_view(), name="accountant-mark-all-notifications-read"),
    path("accountant/analytics/", AccountantAnalyticsDashboardView.as_view(), name="accountant-analytics"),
    path("accountant/analytics/kpis/", AccountantAnalyticsKPIView.as_view(), name="accountant-analytics-kpis"),
    path("accountant/analytics/trends/", AccountantAnalyticsTrendsView.as_view(), name="accountant-analytics-trends"),
    path("accountant/analytics/forecasts/", AccountantAnalyticsForecastsView.as_view(), name="accountant-analytics-forecasts"),
    path("accountant/analytics/insights/", AccountantAnalyticsInsightsView.as_view(), name="accountant-analytics-insights"),
    path("accountant/dashboard-payments/", AccountantDashboardPaymentsView.as_view(), name="accountant-dashboard-payments"),
    path("accountant/pending-partial-payments/", AccountantPendingPartialPaymentsView.as_view(), name="accountant-pending-partial-payments"),
    path("accountant/overdue-payments/", AccountantOverduePaymentsView.as_view(), name="accountant-overdue-payments"),
    path("accountant/total-paid-amount/", AccountantTotalPaidAmountView.as_view(), name="accountant-total-paid-amount"),
    path("accountant/selected-for-invoice/", AccountantSelectedForInvoiceView.as_view(), name="accountant-selected-for-invoice"),
    path("accountant/payment-requests/", AccountantPartialPaymentRequestsView.as_view(), name="accountant-payment-requests"),
    path("accountant/quick-stats/", AccountantQuickStatsView.as_view(), name="accountant-quick-stats"),
    path("accountant/invoices/<uuid:sale_id>/reminders/configure/", PartialInvoiceReminderConfigView.as_view(), name="accountant-invoice-reminder-configure"),
    path("accountant/invoices/<uuid:sale_id>/reminders/send/", PartialInvoiceReminderSendView.as_view(), name="accountant-invoice-reminder-send"),
    path("accountant/invoices/<uuid:sale_id>/reminders/history/", PartialInvoiceReminderHistoryView.as_view(), name="accountant-invoice-reminder-history"),
    path("owner/invoices/<uuid:sale_id>/reminders/configure/", PartialInvoiceReminderConfigView.as_view(), name="owner-invoice-reminder-configure"),
    path("owner/invoices/<uuid:sale_id>/reminders/send/", PartialInvoiceReminderSendView.as_view(), name="owner-invoice-reminder-send"),
    path("owner/invoices/<uuid:sale_id>/reminders/history/", PartialInvoiceReminderHistoryView.as_view(), name="owner-invoice-reminder-history"),
    path("pharmacist/dashboard/", PharmacistDashboardSummaryView.as_view(), name="pharmacist-dashboard"),
    path("pharmacist/pending-invoices/", PharmacistPendingInvoicesView.as_view(), name="pharmacist-pending-invoices"),
    path("pharmacist/recent-approvals/", PharmacistRecentApprovalsView.as_view(), name="pharmacist-recent-approvals"),
    path("pharmacist/invoices/", PharmacistInvoicesListView.as_view(), name="pharmacist-invoices-list"),
    path("pharmacist/invoices/<uuid:invoice_id>/", PharmacistInvoiceDetailView.as_view(), name="pharmacist-invoices-detail"),
    path("pharmacist/invoices/summary/", PharmacistInvoicesSummaryView.as_view(), name="pharmacist-invoices-summary"),
    path("pharmacist/invoices/<uuid:invoice_id>/approve/", PharmacistApproveInvoiceView.as_view(), name="pharmacist-invoices-approve"),
    path("pharmacist/payment-approvals/", PharmacistPaymentApprovalsListView.as_view(), name="pharmacist-payment-approvals"),
    path("pharmacist/invoices/<uuid:invoice_id>/payment/approve/", PharmacistApprovePaymentView.as_view(), name="pharmacist-payment-approve"),
    path("pharmacist/quick-stats/", PharmacistInvoiceQuickStatsView.as_view(), name="pharmacist-quick-stats"),
    path("pharmacist/partial-payments/", PharmacistPartialPaymentsListView.as_view(), name="pharmacist-partial-payments"),
    path("pharmacist/partial-payments/summary/", PharmacistPartialPaymentSummaryView.as_view(), name="pharmacist-partial-payments-summary"),
    path("pharmacist/partial-payments/<uuid:invoice_id>/approve/", PharmacistApprovePartialPaymentView.as_view(), name="pharmacist-partial-payments-approve"),
    path("pharmacist/partial-payments/<uuid:invoice_id>/reject/", PharmacistRejectPartialPaymentView.as_view(), name="pharmacist-partial-payments-reject"),
    path("pharmacist/approval-history/", PharmacistApprovalHistoryListView.as_view(), name="pharmacist-approval-history"),
    path("pharmacist/approval-history/summary/", PharmacistHistorySummaryView.as_view(), name="pharmacist-approval-history-summary"),
    path("pharmacist/approval-history/export/", PharmacistHistoryExportView.as_view(), name="pharmacist-approval-history-export"),
    path("pharmacist/approval-history/search/", PharmacistHistorySearchView.as_view(), name="pharmacist-approval-history-search"),
    path("pharmacist/notifications/", PharmacistRecentNotificationsView.as_view(), name="pharmacist-notifications"),
    path("pharmacist/notifications/<uuid:notification_id>/read/", PharmacistMarkNotificationAsReadView.as_view(), name="pharmacist-mark-notification-read"),
    path("pharmacist/notifications/read-all/", PharmacistMarkAllNotificationsAsReadView.as_view(), name="pharmacist-mark-all-notifications-read"),
    path("owner/partial-payments/", OwnerPartialPaymentsListView.as_view(), name="owner-partial-payments"),
    path("owner/partial-payments/summary/", OwnerPartialPaymentSummaryView.as_view(), name="owner-partial-payments-summary"),
    path("owner/partial-payments/<uuid:invoice_id>/approve/", OwnerApprovePartialPaymentView.as_view(), name="owner-partial-payments-approve"),
    path("owner/partial-payments/<uuid:invoice_id>/reject/", OwnerRejectPartialPaymentView.as_view(), name="owner-partial-payments-reject"),
    path("roles/", RolesListView.as_view(), name="roles-list"),
    path("users/search/", SearchUsersView.as_view(), name="search-users"),
]

urlpatterns += router.urls
